# Backstage documentation
# https://backstage.io/docs/features/software-catalog/descriptor-format/

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: next-test-1
  description: Developing a NextJS Starter
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - nextjs
    - typescript
spec:
  type: website
  lifecycle: experimental
  owner: group:dx-dev
  system: next-test-1
